In [1]:
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.0.1


# Introduction to Tensors

## Tensor Size

In [3]:
# Single number (0-dimensional) that scales a vector, matrix or tensor (a)

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# Array of length n (1-dimensional) that, i.e., represents a plane (y)

vector = torch.tensor([1, 2])
vector

tensor([1, 2])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# 2 nested arrays of n x n size (2-dimensional) that, i.e., represents a vector in a plane (Q)

matrix = torch.tensor([[1, 3], 
                       [1, 2]])
matrix

tensor([[1, 3],
        [1, 2]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
# Multiple nested arrays (N-dimensional) that represents a tensor (X)

tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

In [15]:
tensor2 = torch.tensor([[[[2, 2], [2, 2]], [[2, 2], [2, 2]], [[2, 2], [2, 2]], [[2, 2], [2, 2]]], [[[2, 2], [2, 2]], [[2, 2], [2, 2]], [[2, 2], [2, 2]], [[2, 2], [2, 2]]]])
tensor2

tensor([[[[2, 2],
          [2, 2]],

         [[2, 2],
          [2, 2]],

         [[2, 2],
          [2, 2]],

         [[2, 2],
          [2, 2]]],


        [[[2, 2],
          [2, 2]],

         [[2, 2],
          [2, 2]],

         [[2, 2],
          [2, 2]],

         [[2, 2],
          [2, 2]]]])

In [16]:
tensor2.ndim

4

In [17]:
tensor2.shape

torch.Size([2, 4, 2, 2])

## Random Tensors

In [18]:
## Random tensors

random_tensor = torch.rand(2, 3, 2, 2)
random_tensor

tensor([[[[0.8380, 0.4248],
          [0.0628, 0.5668]],

         [[0.3336, 0.5534],
          [0.7256, 0.2672]],

         [[0.0400, 0.6951],
          [0.2053, 0.9063]]],


        [[[0.4105, 0.9275],
          [0.6768, 0.9716]],

         [[0.8608, 0.0064],
          [0.8859, 0.6739]],

         [[0.2150, 0.4958],
          [0.5927, 0.7660]]]])

In [19]:
## Random tensor for a 128x128 RGB image

random_image_tensor = torch.rand(size=[128, 128, 3])
random_image_tensor.ndim

3

In [20]:
random_image_tensor.shape

torch.Size([128, 128, 3])

In [21]:
random_image_tensor

tensor([[[7.8656e-01, 8.7559e-01, 8.3383e-01],
         [2.7950e-01, 5.4781e-01, 4.5062e-01],
         [4.9213e-01, 2.1988e-01, 8.8580e-01],
         ...,
         [5.2605e-02, 6.6933e-01, 9.4107e-02],
         [2.0365e-01, 1.2129e-01, 7.8500e-01],
         [2.9879e-01, 7.8783e-01, 3.5733e-01]],

        [[2.4391e-01, 6.4862e-02, 6.2952e-01],
         [7.9088e-01, 6.3884e-01, 2.4774e-02],
         [7.8366e-01, 5.4309e-01, 3.1554e-01],
         ...,
         [8.9133e-01, 4.3870e-01, 2.8800e-01],
         [6.7875e-01, 4.1570e-01, 9.5134e-02],
         [9.2726e-01, 2.8585e-01, 4.6724e-02]],

        [[4.1265e-01, 4.7457e-01, 3.4477e-01],
         [9.2879e-02, 2.6687e-01, 9.0517e-01],
         [3.1981e-01, 5.8813e-01, 1.4090e-01],
         ...,
         [8.9312e-01, 2.6633e-01, 6.5043e-01],
         [1.4886e-01, 4.6259e-01, 7.6937e-01],
         [7.2709e-01, 1.8340e-04, 9.1117e-01]],

        ...,

        [[7.1729e-01, 6.6943e-01, 5.4469e-02],
         [7.4601e-01, 4.2964e-01, 1.7027e-01]

In [22]:
## Zeros and ones tensors

zeros_tensor = torch.zeros(size=[1, 3, 3])
ones_tensor = torch.ones(size=[1, 3, 3])
multiply_tensors = zeros_tensor * ones_tensor

In [23]:
zeros_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [24]:
ones_tensor

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [25]:
multiply_tensors

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

## Tensor Datatypes

In [26]:
float32_tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
float32_tensor.dtype

torch.float32

In [27]:
float64_tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0]], dtype=torch.float64)
float64_tensor.dtype

torch.float64

In [28]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor.dtype

torch.float16

In [29]:
float16_tensor*float32_tensor

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [30]:
int32_tensor = float16_tensor.type(torch.int32)
int32_tensor.dtype

torch.int32

## Tensor Attributes (Manipulation)

In [31]:
tensor3 = torch.rand(2, 3)

print(tensor3)
print(f"Data type of tensor: {tensor3.dtype}")
print(f"Size of tensor: {tensor3.shape}")
print(f"Device of tensor: {tensor3.device}")

tensor([[0.9471, 0.4682, 0.2257],
        [0.1024, 0.1660, 0.2835]])
Data type of tensor: torch.float32
Size of tensor: torch.Size([2, 3])
Device of tensor: cpu


In [32]:
tensor3 = tensor3.type(torch.float16)
tensor3 = tensor3.to(device='cuda')
tensor3 = torch.reshape(tensor3, (3, 2))

print(tensor3)
print(f"Data type of tensor: {tensor3.dtype}")
print(f"Size of tensor: {tensor3.shape}")
print(f"Device of tensor: {tensor3.device}")

# Note: reshape works only when original and result have same ammount of elements

tensor([[0.9473, 0.4683],
        [0.2257, 0.1024],
        [0.1660, 0.2834]], device='cuda:0', dtype=torch.float16)
Data type of tensor: torch.float16
Size of tensor: torch.Size([3, 2])
Device of tensor: cuda:0


In [33]:
tensor3 = tensor3.to(device='cpu', dtype=torch.float32)
tensor3 = torch.reshape(tensor3, (1, 6))

print(tensor3)
print(f"Data type of tensor: {tensor3.dtype}")
print(f"Size of tensor: {tensor3.shape}")
print(f"Device of tensor: {tensor3.device}")

tensor([[0.9473, 0.4683, 0.2257, 0.1024, 0.1660, 0.2834]])
Data type of tensor: torch.float32
Size of tensor: torch.Size([1, 6])
Device of tensor: cpu


## Tensor Manipulation

### Unitary Operations

In [34]:
tensor4 = torch.tensor([[1, 3, 5], [7, 9, 11]])

In [35]:
# Addition
tensor4 + 10, torch.add(tensor4, 10)

(tensor([[11, 13, 15],
         [17, 19, 21]]),
 tensor([[11, 13, 15],
         [17, 19, 21]]))

In [36]:
# Subtraction
tensor4 - 10, torch.sub(tensor4, 10)

(tensor([[-9, -7, -5],
         [-3, -1,  1]]),
 tensor([[-9, -7, -5],
         [-3, -1,  1]]))

In [37]:
# Multiplication (Unitary)
tensor4 * 10, torch.mul(tensor4, 10)

(tensor([[ 10,  30,  50],
         [ 70,  90, 110]]),
 tensor([[ 10,  30,  50],
         [ 70,  90, 110]]))

In [38]:
# Division
tensor4 / 10, torch.div(tensor4, 10)

(tensor([[0.1000, 0.3000, 0.5000],
         [0.7000, 0.9000, 1.1000]]),
 tensor([[0.1000, 0.3000, 0.5000],
         [0.7000, 0.9000, 1.1000]]))

### Matrix Multiplication

In [39]:
# Transposed Matrix
tensor4_tr = tensor4.T

print(f"Original Matrix:\n{tensor4}\n{tensor4.shape}\n")
print(f"Transposed Matrix:\n{tensor4.T}\n{tensor4.T.shape}")

# Note: T attribute is the transposed matrix

Original Matrix:
tensor([[ 1,  3,  5],
        [ 7,  9, 11]])
torch.Size([2, 3])

Transposed Matrix:
tensor([[ 1,  7],
        [ 3,  9],
        [ 5, 11]])
torch.Size([3, 2])


In [40]:
tensor4_matmul = torch.matmul(tensor4, tensor4_tr)
tensor4_matmul_opt = tensor4 @ tensor4_tr

print(f"Multiplied Matrixes (matmul):\n{tensor4_matmul}\n{tensor4_matmul.shape}\n")
print(f"Multiplied Matrixes (@):\n{tensor4_matmul_opt}\n{tensor4_matmul_opt.shape}")

# Note: This shows both matmul and @ perform the same operation

Multiplied Matrixes (matmul):
tensor([[ 35,  89],
        [ 89, 251]])
torch.Size([2, 2])

Multiplied Matrixes (@):
tensor([[ 35,  89],
        [ 89, 251]])
torch.Size([2, 2])


In [41]:
tensor4_cpu = torch.rand(5000, 5000, device='cpu')
tensor4_gpu = torch.rand(5000, 5000, device='cuda')

In [42]:
%%time
torch.matmul(tensor4_cpu, tensor4_cpu)

CPU times: total: 2.64 s
Wall time: 470 ms


tensor([[1270.3910, 1239.4879, 1270.8556,  ..., 1264.9307, 1249.3062,
         1252.0669],
        [1269.4742, 1240.2118, 1259.6180,  ..., 1260.7828, 1248.1273,
         1265.8566],
        [1256.2571, 1250.1160, 1268.1534,  ..., 1265.8013, 1257.0520,
         1256.7996],
        ...,
        [1251.2019, 1240.3225, 1258.9095,  ..., 1249.8020, 1250.9424,
         1255.7256],
        [1265.2518, 1261.4303, 1271.9999,  ..., 1269.8590, 1265.4097,
         1259.2592],
        [1239.0614, 1234.3881, 1262.3177,  ..., 1238.6617, 1253.4901,
         1244.6893]])

In [43]:
%%time
torch.matmul(tensor4_gpu, tensor4_gpu)

CPU times: total: 1.12 s
Wall time: 225 ms


tensor([[1253.9142, 1247.1069, 1264.6428,  ..., 1262.2129, 1273.8029,
         1276.9932],
        [1231.5583, 1230.7554, 1249.3975,  ..., 1245.3059, 1247.9601,
         1236.6127],
        [1252.9933, 1242.7959, 1283.0114,  ..., 1263.6041, 1266.8762,
         1250.8005],
        ...,
        [1251.9388, 1240.2405, 1249.8265,  ..., 1262.1411, 1256.9944,
         1256.6808],
        [1259.8948, 1250.7782, 1277.3125,  ..., 1278.1216, 1276.3911,
         1266.3247],
        [1236.0865, 1232.8297, 1266.3579,  ..., 1261.4054, 1245.4670,
         1251.6779]], device='cuda:0')

## Statistics of a Tensor

### min(), max(), sum(), median() and mean()

In [44]:
tensor5 = torch.tensor([0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100], dtype=torch.float32)
tensor5

tensor([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [45]:
# Max

print(f"Max: {tensor5.max()}")
print(f"Position of max (argmax): {tensor5.argmax()}")

Max: 100.0
Position of max (argmax): 10


In [46]:
# Min

print(f"Min: {tensor5.min()}")
print(f"Position of min (argmin): {tensor5.argmin()}")

Min: 0.0
Position of min (argmin): 0


In [47]:
# Others

print(f"Sum: {tensor5.sum()}")
print(f"Median: {tensor5.median()}")
print(f"Mean: {tensor5.mean()}")

Sum: 550.0
Median: 50.0
Mean: 50.0


In [48]:
tensor6 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], dtype=torch.float32)
tensor6

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [49]:
# Stats from this new tensor

print(f"Max: {tensor6.max()}")
print(f"Position of max (argmax): {tensor6.argmax()}")
print(f"Min: {tensor6.min()}")
print(f"Position of min (argmin): {tensor6.argmin()}")
print(f"Sum: {tensor6.sum()}")
print(f"Median: {tensor6.median()}")
print(f"Mean: {tensor6.mean()}")

Max: 12.0
Position of max (argmax): 11
Min: 1.0
Position of min (argmin): 0
Sum: 78.0
Median: 6.0
Mean: 6.5


## Tensor Combination and Resizing

### Reshape

In [50]:
# Reshaping: Transform a tensor into a new one with a different legal shape

tensor7 = torch.arange(1, 50, 4.3)
print(tensor7)
print(tensor7.size())

tensor([ 1.0000,  5.3000,  9.6000, 13.9000, 18.2000, 22.5000, 26.8000, 31.1000,
        35.4000, 39.7000, 44.0000, 48.3000])
torch.Size([12])


In [51]:
tensor7_reshape1 = tensor7.reshape(2, 6)
print(tensor7_reshape1)
print(tensor7_reshape1.size())

tensor([[ 1.0000,  5.3000,  9.6000, 13.9000, 18.2000, 22.5000],
        [26.8000, 31.1000, 35.4000, 39.7000, 44.0000, 48.3000]])
torch.Size([2, 6])


In [52]:
tensor7_reshape2 = tensor7.reshape(2, 2, 3)
print(tensor7_reshape2)
print(tensor7_reshape2.size())

tensor([[[ 1.0000,  5.3000,  9.6000],
         [13.9000, 18.2000, 22.5000]],

        [[26.8000, 31.1000, 35.4000],
         [39.7000, 44.0000, 48.3000]]])
torch.Size([2, 2, 3])


### View

In [53]:
# View: Same as the reference to an object (tensor). Modifications to a view's VALUES, modify the original's

tensor7_view = tensor7.view(12)
tensor7_view[:7] = 1.77
tensor7_view = tensor7_view.reshape(2, 6)
print(f"Tensor 7 view: {tensor7_view}")
print(f"Tensor 7: {tensor7}")

Tensor 7 view: tensor([[ 1.7700,  1.7700,  1.7700,  1.7700,  1.7700,  1.7700],
        [ 1.7700, 31.1000, 35.4000, 39.7000, 44.0000, 48.3000]])
Tensor 7: tensor([ 1.7700,  1.7700,  1.7700,  1.7700,  1.7700,  1.7700,  1.7700, 31.1000,
        35.4000, 39.7000, 44.0000, 48.3000])


### Vertical Stacking (vstack)

In [54]:
# Stack: concatenates tensors as defined in the input

tensor7_stack = torch.stack([tensor7, tensor7, tensor7, tensor7])
print(f"Stack of dim 0: {tensor7_stack}\nShape: {tensor7_stack.shape}")

Stack of dim 0: tensor([[ 1.7700,  1.7700,  1.7700,  1.7700,  1.7700,  1.7700,  1.7700, 31.1000,
         35.4000, 39.7000, 44.0000, 48.3000],
        [ 1.7700,  1.7700,  1.7700,  1.7700,  1.7700,  1.7700,  1.7700, 31.1000,
         35.4000, 39.7000, 44.0000, 48.3000],
        [ 1.7700,  1.7700,  1.7700,  1.7700,  1.7700,  1.7700,  1.7700, 31.1000,
         35.4000, 39.7000, 44.0000, 48.3000],
        [ 1.7700,  1.7700,  1.7700,  1.7700,  1.7700,  1.7700,  1.7700, 31.1000,
         35.4000, 39.7000, 44.0000, 48.3000]])
Shape: torch.Size([4, 12])


In [55]:
# Stack of dim 1: dim defines in what dimension (position of shape vector) shall the stacking occur

tensor7_stack1 = torch.stack([tensor7, tensor7, tensor7, tensor7], dim=1)
print(f"Stack of dim 1: {tensor7_stack1}\nShape: {tensor7_stack1.shape}")

Stack of dim 1: tensor([[ 1.7700,  1.7700,  1.7700,  1.7700],
        [ 1.7700,  1.7700,  1.7700,  1.7700],
        [ 1.7700,  1.7700,  1.7700,  1.7700],
        [ 1.7700,  1.7700,  1.7700,  1.7700],
        [ 1.7700,  1.7700,  1.7700,  1.7700],
        [ 1.7700,  1.7700,  1.7700,  1.7700],
        [ 1.7700,  1.7700,  1.7700,  1.7700],
        [31.1000, 31.1000, 31.1000, 31.1000],
        [35.4000, 35.4000, 35.4000, 35.4000],
        [39.7000, 39.7000, 39.7000, 39.7000],
        [44.0000, 44.0000, 44.0000, 44.0000],
        [48.3000, 48.3000, 48.3000, 48.3000]])
Shape: torch.Size([12, 4])


In [56]:
# Stack of dim 2

tensor7 = tensor7.reshape(2, 2, 3)
tensor7_stack2 = torch.stack([tensor7, tensor7, tensor7, tensor7], dim=2)
print(f"New tensor 7: {tensor7}\nShape: {tensor7.shape}\n")
print(f"Stack of dim 1: {tensor7_stack2}\nShape: {tensor7_stack2.shape}")

New tensor 7: tensor([[[ 1.7700,  1.7700,  1.7700],
         [ 1.7700,  1.7700,  1.7700]],

        [[ 1.7700, 31.1000, 35.4000],
         [39.7000, 44.0000, 48.3000]]])
Shape: torch.Size([2, 2, 3])

Stack of dim 1: tensor([[[[ 1.7700,  1.7700,  1.7700],
          [ 1.7700,  1.7700,  1.7700],
          [ 1.7700,  1.7700,  1.7700],
          [ 1.7700,  1.7700,  1.7700]],

         [[ 1.7700,  1.7700,  1.7700],
          [ 1.7700,  1.7700,  1.7700],
          [ 1.7700,  1.7700,  1.7700],
          [ 1.7700,  1.7700,  1.7700]]],


        [[[ 1.7700, 31.1000, 35.4000],
          [ 1.7700, 31.1000, 35.4000],
          [ 1.7700, 31.1000, 35.4000],
          [ 1.7700, 31.1000, 35.4000]],

         [[39.7000, 44.0000, 48.3000],
          [39.7000, 44.0000, 48.3000],
          [39.7000, 44.0000, 48.3000],
          [39.7000, 44.0000, 48.3000]]]])
Shape: torch.Size([2, 2, 4, 3])


### Squeeze, Unsqueeze and Permutation

In [57]:
# Squeeze: removes all dimensions of length 1

tensor7 = tensor7.reshape(1, 1, 2, 2, 1, 3)
tensor7_squeeze = tensor7.squeeze()
print(f"Before squeeze: {tensor7}\nShape: {tensor7.shape}\n")
print(f"After squeeze: {tensor7_squeeze}\nShape: {tensor7_squeeze.shape}")

Before squeeze: tensor([[[[[[ 1.7700,  1.7700,  1.7700]],

           [[ 1.7700,  1.7700,  1.7700]]],


          [[[ 1.7700, 31.1000, 35.4000]],

           [[39.7000, 44.0000, 48.3000]]]]]])
Shape: torch.Size([1, 1, 2, 2, 1, 3])

After squeeze: tensor([[[ 1.7700,  1.7700,  1.7700],
         [ 1.7700,  1.7700,  1.7700]],

        [[ 1.7700, 31.1000, 35.4000],
         [39.7000, 44.0000, 48.3000]]])
Shape: torch.Size([2, 2, 3])


In [58]:
# Unsqueeze: adds a dimension at the specified dimension

tensor7_unsqueeze = tensor7_squeeze.unsqueeze(dim=1)
print(f"Before unsqueeze: {tensor7_squeeze}\nShape: {tensor7_squeeze.shape}\n")
print(f"After unsqueeze: {tensor7_unsqueeze}\nShape: {tensor7_unsqueeze.shape}")

Before unsqueeze: tensor([[[ 1.7700,  1.7700,  1.7700],
         [ 1.7700,  1.7700,  1.7700]],

        [[ 1.7700, 31.1000, 35.4000],
         [39.7000, 44.0000, 48.3000]]])
Shape: torch.Size([2, 2, 3])

After unsqueeze: tensor([[[[ 1.7700,  1.7700,  1.7700],
          [ 1.7700,  1.7700,  1.7700]]],


        [[[ 1.7700, 31.1000, 35.4000],
          [39.7000, 44.0000, 48.3000]]]])
Shape: torch.Size([2, 1, 2, 3])


In [59]:
# Permutation: shifts the dimensions' axis to a new specified permutation

tensor8 = torch.rand(size=[128, 128, 3])
tensor8_permute = tensor8.permute(2, 0, 1)
print(f"Old shape: {tensor8.shape}")
print(f"New shape: {tensor8_permute.shape}")

# Explanation: 2nd index dim shifts to 0th index dimension in new tensor, 0th to 1st and 1st to 2nd

Old shape: torch.Size([128, 128, 3])
New shape: torch.Size([3, 128, 128])


## Tensor Indexing

In [60]:
# Indexing: Same as getting list indexes

tensor9 = torch.arange(1, 10).reshape(1, 3, 3)
tensor9

# Note: Pytorch tensors aren't the same as Python's (Pytorch -> index dimensions; Python -> index array)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [61]:
# Select first element of the tensor

tensor9[0][0][0], tensor9[0, 0, 0]

(tensor(1), tensor(1))

In [62]:
# Select last array of the tensor
# Note: The semicolon (:) selects all elements in that dimension

tensor9[0][-1], tensor9[0, -1, :]

(tensor([7, 8, 9]), tensor([7, 8, 9]))

In [63]:
# Select all the 2nd values of each 0th dimension

tensor9[0, :, 1]

tensor([2, 5, 8])

In [64]:
# Select the last 2 values of the first 2 dimensions

tensor9[0, :2, 1:]

tensor([[2, 3],
        [5, 6]])

## PyTorch and NumPy 

In [65]:
# Numpy arrays and the from_numpy method
# Note: This aims to show that PyTorch inherits the NumPy array data types and vice-versa

array1 = np.arange(1.0, 10.0)
tensor10 = torch.from_numpy(array1)
print(f"NumPy array: {array1}\nData Type: {array1.dtype}")
print(f"PyTorch tensor: {tensor10}\nData Type: {tensor10.dtype}")

NumPy array: [1. 2. 3. 4. 5. 6. 7. 8. 9.]
Data Type: float64
PyTorch tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)
Data Type: torch.float64


In [66]:
# Pytorch arrays and numpy method

tensor11 = torch.rand(size=[5])
array2 = tensor11.numpy()
print(f"PyTorch tensor: {tensor11}\nData Type: {tensor11.dtype}")
print(f"NumPy array: {array2}\nData Type: {array2.dtype}")

PyTorch tensor: tensor([0.1377, 0.0520, 0.8290, 0.1684, 0.0207])
Data Type: torch.float32
NumPy array: [0.13769823 0.05196977 0.8290323  0.16839749 0.02068156]
Data Type: float32


## Reproducing results (non-random random tensors)

In [67]:
# The rand() method generates a pseudorandom tensor based on a random seed

tensor12 = torch.rand(size=[3, 3])
tensor13 = torch.rand(size=[3, 3])

print(f"{tensor12}\n")
print(f"{tensor13}\n")
print(tensor12 == tensor13)

tensor([[0.3648, 0.6557, 0.6869],
        [0.1514, 0.9014, 0.7746],
        [0.8258, 0.3828, 0.9701]])

tensor([[0.2080, 0.4705, 0.7515],
        [0.9977, 0.3006, 0.0906],
        [0.5786, 0.1825, 0.6317]])

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [68]:
# manual_seed(): The next random tensor will be generated on the given seed (argument)

SEED = 42
torch.manual_seed(SEED)
tensor14 = torch.rand(size=[4, 3])
torch.manual_seed(SEED)
tensor15 = torch.rand(size=[4, 3])

print(f"{tensor14}\n")
print(f"{tensor15}\n")
print(tensor14 == tensor15)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])


# Setting up (device agnostic code)

In [69]:
!nvidia-smi

Tue Oct 10 23:00:35 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.99                 Driver Version: 536.99       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1050 Ti   WDDM  | 00000000:01:00.0  On |                  N/A |
| 28%   36C    P0              N/A /  75W |   1336MiB /  4096MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [70]:
# Check if GPU is available

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [71]:
# Number of GPUs

torch.cuda.device_count()

1

In [72]:
# Applying agnostic code

test_tensor = torch.rand(size=[3, 4])
print(f"Initial device: {test_tensor.device}")
test_tensor = test_tensor.to(device)
print(f"New device: {test_tensor.device}")

Initial device: cpu
New device: cuda:0


In [73]:
# NumPy and GPUs

test_array = test_tensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [74]:
test_tensor = test_tensor.cpu()
test_array = test_tensor.numpy()
test_array

# Note: This aims to show that conversions between numpy and pytorch can only occur in CPU

array([[0.86940444, 0.5677153 , 0.74109405, 0.4294045 ],
       [0.8854429 , 0.57390445, 0.26658005, 0.62744915],
       [0.26963168, 0.44136357, 0.29692084, 0.8316855 ]], dtype=float32)

# Exercises

### 1. Create a random tensor with shape (7, 7)

In [76]:
tensor16 = torch.rand(size=[7, 7])
tensor16

tensor([[0.0874, 0.0041, 0.1088, 0.1637, 0.7025, 0.6790, 0.9155],
        [0.2418, 0.1591, 0.7653, 0.2979, 0.8035, 0.3813, 0.7860],
        [0.1115, 0.2477, 0.6524, 0.6057, 0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578, 0.3313, 0.3227, 0.0162, 0.2137],
        [0.6249, 0.4340, 0.1371, 0.5117, 0.1585, 0.0758, 0.2247],
        [0.0624, 0.1816, 0.9998, 0.5944, 0.6541, 0.0337, 0.1716],
        [0.3336, 0.5782, 0.0600, 0.2846, 0.2007, 0.5014, 0.3139]])

### 2. Perform a matrix multiplication on the tensor from 1 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor)

In [79]:
tensor17 = torch.rand(size=[1, 7]).T
tensor16.matmul(tensor17)

tensor([[1.4878],
        [1.9067],
        [1.7285],
        [1.1695],
        [0.6551],
        [1.4879],
        [0.6377]])

### 3. Set the random seed to 0 and do 1 & 2 over again

In [93]:
torch.manual_seed(0)
tensor16 = torch.rand(size=[7, 7])
tensor17 = torch.rand(size=[1, 7]).T

tensor16.matmul(tensor17)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 4. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [83]:
torch.cuda.manual_seed(0)
tensor18 = torch.rand(size=[3, 3], device='cuda')
tensor18

tensor([[0.3990, 0.5167, 0.0249],
        [0.9401, 0.9459, 0.7967],
        [0.4150, 0.8203, 0.2290]], device='cuda:0')

### 5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed)

In [94]:
torch.manual_seed(1234)
tensor19 = torch.rand(size=[2, 3])
tensor20 = torch.rand(size=[2, 3])

device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor19 = tensor19.to(device)
tensor20 = tensor20.to(device)

print(f"Tensor 19 device: {tensor19.device}")
print(f"Tensor 20 device: {tensor20.device}")

Tensor 19 device: cuda:0
Tensor 20 device: cuda:0


### 6. Perform a matrix multiplication on the tensors you created in 5 (again, you may have to adjust the shapes of one of the tensors)

In [95]:
tensor21 = tensor19.matmul(tensor20.T)
tensor21

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 7. Find the maximum and minimum values of the output of 6

In [96]:
print(f"Min: {tensor21.min()}")
print(f"Max: {tensor21.max()}")

Min: 0.3647301495075226
Max: 0.5617256760597229


### 8. Find the maximum and minimum index values of the output of 6

In [97]:
print(f"Position of min: {tensor21.argmin()}")
print(f"Position of min: {tensor21.argmax()}")

Position of min: 0
Position of min: 3


### 9. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape

In [98]:
torch.manual_seed(7)
tensor22 = torch.rand(size=[1, 1, 1, 10])
tensor23 = torch.squeeze(tensor22)

print(tensor22)
print(tensor22.shape)
print(tensor23)
print(tensor23.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
